### PR TITLE
Ionyshch/fixes 20170106

### PR DESCRIPTION
**Pull request by ionyshch-prismsl**

### CODE REVIEW

**Comment by andrii-prism** [comment]
1) boost version is not checked. CMake needs to check boost > 1.6
2) yt_camera does not work out of the box
    dyld: Library not loaded: libboost_system.dylib
  Referenced from: /Users/andrii/work/prism-connect-new/build/examples/yt_camera/./yt_camera
  Reason: image not found
Abort trap: 6

**Comment by Yurmusp** [comment]
You may need to specify DYLD_LIBRARY_PATH to have SO libs hooked up
properly.
Because specifying rpath makes no sense.
So, only options are DYLD_LIBRARY_PATH or have libs linked statically.

**Comment by ionyshch-prismsl** [comment]
Andrii, what is output from running cmake?

**Comment by bvnp44** [comment]
Can we use static boost libs, not dynamic?

set(Boost_USE_STATIC_LIBS ON)
set(Boost_USE_MULTITHREADED ON)
set(Boost_USE_STATIC_RUNTIME ON)

find_package(Boost 1.60.0 REQUIRED COMPONENTS ....

**Comment by ionyshch-prismsl** [comment]
Yes, we can.
I've made changes. Please, take a look

**Comment by bvnp44** [comment]
Please try to find why you need to define BOOST_ROOT, it should work without it like it works in Virtual Camera. I commented it in cmake on my machine and it compiled successfully

**Comment by ionyshch-prismsl** [comment]
Changed to using BOOST_ROOT only if Boost isn't found without it

**Pull request merged**
